# nginx1.conf (первый, кто видит пользователя)
events { worker_connections 1024; }

http {
    server {
        listen 80;
        
        location / {
            # Игнорируем пользовательский XFF полностью
            # Начинаем цепочку с реального IP
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_pass http://nginx2:80;
        }
    }
}
