# nginx2.conf, nginx3.conf ... nginx10.conf (внутренние)
events { worker_connections 1024; }

http {
    server {
        listen 80;
        
        location / {
            # Добавляем свой IP к цепочке
            proxy_set_header X-Forwarded-For "$http_x_forwarded_for, $remote_addr";
            proxy_pass http://nginx3:80;
        }
    }
}
